version: '3.8'

services:
  azr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absolute-zero-reasoner
    volumes:
      - .:/workspace
      - ./data:/workspace/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8888:8888"  # Jupyter Notebook
      - "6006:6006"  # TensorBoard
    command: tail -f /dev/null  # 컨테이너를 계속 실행 상태로 유지